services:
  url_shortener:
    image: url_shortener
    pull_policy: never
    container_name: url_shortener-backend
    build: 
      context: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - mongo-express
  
  db:
    image: mongo:latest
    container_name: url_shortener-mongodb
    ports:
      - "27017:27017"
    expose:
      - 27017
    volumes:
      - db-data:/data/db
    env_file:
      - ./db/.env

  mongo-express:
    image: mongo-express:latest
    container_name: url_shortener-mongo-express
    ports:
      - "8081:8081"
    env_file:
      - ./mongo-express/.env
    depends_on:
      - db

volumes:
  db-data: